wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.9
    cli_version: 0.19.7.dev1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1743777604
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 105
      3:
      - 14
      - 23
      4: 3.12.9
      5: 0.19.7.dev1
      8:
      - 5
      13: darwin-arm64
batch_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 8
hidden_size:
  desc: null
  value: 128
input_size:
  desc: null
  value: 28
learning_rate:
  desc: null
  value: 0.016653689553524503
output_size:
  desc: null
  value: 16
