wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.9
    cli_version: 0.19.7.dev1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1743528342
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 55
      - 105
      3:
      - 14
      - 16
      - 23
      - 37
      4: 3.12.9
      5: 0.19.7.dev1
      8:
      - 5
      13: darwin-arm64
input_size:
  desc: null
  value: 28
hidden_size:
  desc: null
  value: 64
output_size:
  desc: null
  value: 16
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.003308125453680346
epochs:
  desc: null
  value: 10
