_wandb:
    value:
        cli_version: 0.19.7.dev1
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 53
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.7.dev1
            "8":
                - 5
            "12": 0.19.7.dev1
            "13": darwin-arm64
batch_size:
    value: 64
epochs:
    value: 10
hidden_size:
    value: 128
input_size:
    value: 28
learning_rate:
    value: 0.001
output_size:
    value: 16
